package com.halit;

public enum ECountries {
	TURKIYE, FRANCE, GERMANY, ENGLAND, NETHERLANDS, HUNGARY, GREECE, ITALY, NORWAY, SWEDEN, SWITZERLAND, RUSSIA, SPAIN,
	UKRAINE, POLAND, BELGIUM, PORTUGAL, AUSTRIA, DENMARK, BULGARIA

}
